### ISSUE TITLE
怎么给proxy使用type: url-test 模式呢？

### ISSUE THREAD

**Issue by llity** [yeehonglee/Clash-Template-Config#1]
想增加自动切换节点的功能，谢谢

**Comment by llity** [comment]
能通用吗？不是Windows平台怎么初始化使用哦。

**Comment by zuluion** [comment]
> 想增加自动切换节点的功能，谢谢

自动切换节点，只需将需要自动切换节点的策略组类型有 select 改成 url-test 即可，参考clash 官方文档 https://lancellc.gitbook.io/clash/clash-config-file/proxy-groups/auto

**Comment by zuluion** [comment]
> 能通用吗？不是Windows平台怎么初始化使用哦。

需要在clash 主目录下创建 两个目录 ，即
`.\myprovider\proxies`
`.\myprovider\ruleset`
并且下载项目中的 `provider-airport.yml` 放置与 `.\myprovider\proxies` 此目录中

**Comment by zuluion** [comment]
Problem Resolution

**Comment by llity** [comment]
谢谢，可以了。我用的自建结点！

**Comment by llity** [comment]
这样的写法非常简洁，喜欢。
