### ISSUE TITLE
多个订阅链接可以填在一起吗？用什么符号分割

### ISSUE THREAD

**Issue by rentry00** [yeehonglee/Clash-Template-Config#4]
多个订阅链接可以填在一起吗？用什么符号分割

**Comment by zuluion** [comment]
>已在 commit 2f7d066 中已解决

# 红框内容需要取消注释，此提交仅 支持第二个订阅 

![image](https://github.com/user-attachments/assets/3324b89c-de58-4747-823e-09103bf64af0)

如果需要更多订阅，可以参考此次提交自行修改模板，如果有更好方案也欢迎pr

>多个订阅我比较建议使用sub-store进行管理，目前 [mihomo-party](https://github.com/mihomo-party-org/mihomo-party) 客户端已经集成了sub-store，可以考虑使用
