### ISSUE TITLE
订阅中hysteria2协议的节点会丢失

### ISSUE THREAD

**Issue by B416-JAFLY** [yeehonglee/Clash-Template-Config#6]
是不是尚不支持新协议的缘故？这个是预期内的嘛

**Comment by zuluion** [comment]
本仓库只是一个配置模板，通常和节点丢失无关，除非是节点名称过滤问题。

排查节点名称过滤问题 可以在 策略组 AIRPORT 中看能否找到你说的节点，这个策略组没有启用filter字段。

如果非上述问题，建议检查你的客户端是否是 mihomo 内核，https://wiki.metacubex.one/config/proxies/hysteria2/ 新版本是支持hysteria2协议的。其他支持Clash配置的客户端建议查看客户端文档排查是否支持此协议。

**Comment by B416-JAFLY** [comment]
排查了下，策略组 AIRPORT 中有“过滤掉2条线路”，应该就是丢失的那两条，检查了下原订阅，这两条节点的格式是形式如：
- { name: 日本直连接入点-B02, server: jp2****.xyz, port: 443, sni: jp2****.xyz, up: 1024, down: 1024, skip-cert-verify: false, type: hysteria2, password: **** }这样的结构，会不会是这个原因导致被过滤掉了？

检查了下，我目前使用的是clash verge 1.7.7, mihomo内核1.18.7，直接添加机场订阅可以显示hysteria2节点，方便帮忙看下可能是什么原因吗

**Comment by zuluion** [comment]
应确保 proxy provider 格式正确，你提供的那个缺少了 ”“ 
```
proxies:
  - {"name":"日本直连接入点-B02", "server": "jp2****.xyz", "port": 443, "sni": "jp2****.xyz", "up": 1024, "down": 1024, "skip-cert-verify": false, "type": "hysteria2", "password: ****" }
```

**Comment by zuluion** [comment]
> 应确保 proxy provider 格式正确，你提供的那个缺少了 ”“
> 
> ```
> proxies:
>   - {"name":"日本直连接入点-B02", "server": "jp2****.xyz", "port": 443, "sni": "jp2****.xyz", "up": 1024, "down": 1024, "skip-cert-verify": false, "type": "hysteria2", "password: ****" }
> ```

需要注意一下 上一条回复中我引号没打全 ，应该是
```
proxies:
  - {"name":"日本直连接入点-B02", "server": "jp2****.xyz", "port": 443, "sni": "jp2****.xyz", "up": 1024, "down": 1024, "skip-cert-verify": false, "type": "hysteria2", "password": "****" }
```


--- 

实际测试发现 clash-verge-rev 解析校验应该是更严格一些

格式正确时是可以正常解析到的
![image](https://github.com/user-attachments/assets/cf14e720-29b8-44ca-9e68-2c697eb5a20c)

![image](https://github.com/user-attachments/assets/34269e39-0628-4bc1-98e2-6721bab9b409)

![image](https://github.com/user-attachments/assets/38a2aa9b-d252-414a-84a6-366f72ba84c5)

---

而你提供的格式，效果如下

1. 格式：
  ```
proxies:
    - { name: 日本直连接入点-B02, server: jp2****.xyz, port: 443, sni: jp2****.xyz, up: 1024, down: 1024, skip-cert-verify: false, type: hysteria2, password: **** }

```
2. 效果：
![image](https://github.com/user-attachments/assets/4436f5dd-33b7-47cb-9d0e-ded6d5d33e03)
![image](https://github.com/user-attachments/assets/352a7337-850c-4817-93e8-89500717cf67)


ps. 此外，发现clash-verge-rev 疑似bug，点击更新代理集合时实际没有更新成功

---

建议解决方案：
**如果你的机场提供的订阅格式不规范的话，建议通过订阅转换 或则 sub-store，mihomo-party现在集成了sub-store，可以方便进行节点格式转换，gui-for-clash 也有sub-store插件可用，然后将转换结果同步到你的gist，在配置文件中使用你的gist url**

**Comment by B416-JAFLY** [comment]
感谢感谢，检查了一下确实是都没带上引号，我去了解下mihomo-party
